language: java
jdk:
  - oraclejdk8

env:
  - PROFILE=build
  - PROFILE=build,googlechrome
  - PROFILE=build,firefox
  - PROFILE=build,googlechromeheadless
  - PROFILE=build,firefoxheadless
  
stages:
  - test
  - name: deploySnapshot
    if: branch = develop
  - name: deployRelease
    if: tag IS present
        
addons:
  chrome: stable
  firefox: latest

before_install:
  - if [ ! -z "$GPG_SECRET_KEYS" ]; then echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import; fi
  - if [ ! -z "$GPG_OWNERTRUST" ]; then echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust; fi
  - sudo apt-get -qq update
  - sudo apt-get install -y dbus-x11
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  
install: mvn --settings .travis/settings.xml verify -Dgpg.skip -B -V -P$PROFILE
script: skip
    
jobs:
  include:
    - stage: deploySnapshot
      addons: skip
      install: skip
      script: skip
      deploy:
        provider: script
        script: .travis/deploy.sh
        skip_cleanup: true
        on:
          repo: Hi-Fi/robotframework-seleniumlibrary-java
          branch: develop
    - stage: deployRelease
      addons: skip
      install: skip
      script: skip
      deploy:
        provider: script
        script: .travis/deploy.sh
        skip_cleanup: true
        on:
          repo: Hi-Fi/robotframework-seleniumlibrary-java
          tags: true